language: ruby
script: "./build.sh"
branches:
  only:
  - jekyll
rvm:
- 2.2.0
env:
  global:
    secure: Y/jslpSN+2abltOUSocohxDr0rAPPcH4mnW44AURkRvCf7nqQ00UiNtJIJV0uySUssVsKDqT0Pjm0xoTOf5LupovRdUi+Uj2TnSB7PMh+VirSzMcNvTTHyQGR3W2sx8Wkju+bacmLKOyL5HqjUGLM6qgaquE6DTOLBo0FmCJJXw=
